galaxy_info:
  role_name: RKE Cluster
  author: Jesús Furió
  description: An Ansible Role that setup Development RKE Cluster.
  license: MIT

  min_ansible_version: 2.9

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
  - name: Ubuntu
    versions:
    - bionic
  - name: OpenSUSE
    versions:
    - Leap 15.3
  galaxy_tags: 
    - docker
    - kubernetes
    - rke
dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
  