---
- name: System config
  include_tasks: "./tasks/config-system.yml"

- name: Installing Docker (Ubuntu)
  include_tasks: "./tasks/install-docker-ubuntu.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Installing Docker (OpenSuse)
  include_tasks: "./tasks/install-docker-suse.yml"
  when: ansible_os_family == 'Suse'

- name: Creating cluster with RKE
  include_tasks: "./tasks/deploy_cluster.yml"